const data = { 
  status: "success",
  items: [
    {
      id: 1,
      title: "Soval Ref.A48",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img01.jpg'),
      category: "blusas",
    },
    {
      id: 2,
      title: "Soval Ref.098",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img02.jpg'),
      category: "blusas",
    },
    {
      id: 3,
      title: "Soval Ref.095",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img03.jpg'),
      category: "blusas",
    },
    {
      id: 4,
      title: "Soval Ref.A66",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img04.jpg'),
      category: "blusas",
    },
    {
      id: 5,
      title: "Soval Ref.108",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img05.jpg'),
      category: "blusas",
    },
    {
      id: 6,
      title: "Soval Ref.A61",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img06.jpg'),
      category: "blusas",
    },
    {
      id: 7,
      title: "Soval Ref.109",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img07.jpg'),
      category: "blusas",
    },
    {
      id: 8,
      title: "Soval.Ref 113",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img020.jpg'),
      category: "blusas",
    },
    {
      id: 9,
      title: "Soval.Ref 136",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img021.jpg'),
      category: "blusas",
    },
    {
      id: 10,
      title: "Soval Ref.A56",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img022.jpg'),
      category: "blusas",
    },
    {
      id: 11,
      title: "Soval Ref.115",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img023.jpg'),
      category: "blusas",
    },
    {
      id: 12,
      title: "Soval Ref.093",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img024.jpg'),
      category: "blusas",
    },
    {
      id: 13,
      title: "Soval Ref.095",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img012.jpg'),
      category: "blusas",
    },
    {
      id: 14,
      title: "Soval Ref.141",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img013.jpg'),
      category: "blusas",
    },
    {
      id: 15,
      title: "Soval Ref.A54",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img014.jpg'),
      category: "blusas",
    },
    {
      id: 16,
      title: "Soval Ref.A57",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img015.jpg'),
      category: "blusas",
    },
    {
      id: 17,
      title: "Soval Ref.137",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img016.jpg'),
      category: "blusas",
    },
    {
      id: 18,
      title: "Soval Ref.105",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img017.jpg'),
      category: "blusas",
    },
    {
      id: 19,
      title: "Soval Ref.109",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img018.jpg'),
      category: "blusas",
    },
    {
      id: 20,
      title: "Soval Ref.140",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img019.jpg'),
      category: "blusas",
    },
    {
      id: 21,
      title: "Soval Ref.151",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img025.jpg'),
      category: "blusas",
    },
    {
      id: 22,
      title: "Soval Ref.139",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img026.jpg'),
      category: "blusas",
    },
    {
      id: 23,
      title: "Soval Ref.150",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img027.jpg'),
      category: "blusas",
    },
    {
      id: 24,
      title: "Soval Ref.028",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img028.jpg'),
      category: "blusas",
    },
    {
      id: 25,
      title: "Soval Ref.A58",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img029.jpg'),
      category: "blusas",
    },
    {
      id: 26,
      title: "Soval Ref.04",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img030.jpg'),
      category: "blusas",
    },
    {
      id: 27,
      title: "Soval Ref.142",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img031.jpg'),
      category: "blusas",
    },
    {
      id: 28,
      title: "Soval Ref.070",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img032.jpg'),
      category: "blusas",
    },
    {
      id: 29,
      title: "Soval Ref.097",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img033.jpg'),
      category: "blusas",
    },
    {
      id: 30,
      title: "Soval Ref.138",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img035.jpg'),
      category: "blusas",
    },
    {
      id: 31,
      title: "Soval Ref.A48",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img036.jpg'),
      category: "blusas",
    },
    {
      id: 32,
      title: "Soval Ref.108",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img037.jpg'),
      category: "blusas",
    },
    {
      id: 33,
      title: "Soval Ref.06",
      priceUnit: 100000,
      cantidad: 1,
      image: require('./images/img038.jpg'),
      category: "blusas",
    },
  ],
};

export default data;
