const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Soval Ref.A48",
      priceUnit: 4000,
      priceWholesale: 3500,
      cantidad: 1,
      image: require('./images/img01.jpg'),
      category: "blusas",
    },
    {
      id: 2,
      title: "Soval Ref.A25",
      priceUnit: 3040,
      priceWholesale: 280,
      cantidad: 1,
      image: require('./images/img02.jpg'),
      category: "blusas",
    },
    {
      id: 3,
      title: "Soval Ref.095",
      priceUnit: 4700,
      priceWholesale: 4200,
      cantidad: 1,
      image: require('./images/img03.jpg'),
      category: "blusas",
    },
    {
      id: 4,
      title: "Soval Ref.A66",
      priceUnit: 399,
      priceWholesale: 360,
      cantidad: 1,
      image: require('./images/img04.jpg'),
      category: "blusas",
    },
    {
      id: 5,
      title: "Soval Ref.108",
      priceUnit: 405,
      priceWholesale: 370,
      cantidad: 1,
      image: require('./images/img05.jpg'),
      category: "blusas",
    },
    {
      id: 6,
      title: "Soval Ref.A61",
      priceUnit: 285,
      priceWholesale: 250,
      cantidad: 1,
      image: require('./images/img06.jpg'),
      category: "blusas",
    },
    {
      id: 7,
      title: "Soval Ref.109",
      priceUnit: 360,
      priceWholesale: 330,
      cantidad: 1,
      image: require('./images/img07.jpg'),
      category: "blusas",
    },
    {
      id: 8,
      title: "Soval.Ref 113",
      priceUnit: 3355,
      priceWholesale: 3000,
      cantidad: 1,
      image: require('./images/img020.jpg'),
      category: "blusas",
    },
    {
      id: 9,
      title: "Soval.Ref 136",
      priceUnit: 7999,
      priceWholesale: 7000,
      cantidad: 1,
      image: require('./images/img021.jpg'),
      category: "blusas",
    },
    {
      id: 10,
      title: "Soval Ref.A56",
      priceUnit: 501,
      priceWholesale: 450,
      cantidad: 1,
      image: require('./images/img022.jpg'),
      category: "blusas",
    },
    {
      id: 11,
      title: "Soval Ref.115",
      priceUnit: 377,
      priceWholesale: 340,
      cantidad: 1,
      image: require('./images/img023.jpg'),
      category: "blusas",
    },
    {
      id: 12,
      title: "Soval Ref.093",
      priceUnit: 377,
      priceWholesale: 340,
      cantidad: 1,
      image: require('./images/img024.jpg'),
      category: "blusas",
    },
    {
      id: 13,
      title: "Soval Ref.095",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img012.jpg'),
      category: "blusas",
    },
    {
      id: 14,
      title: "Soval Ref.141",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img013.jpg'),
      category: "blusas",
    },
    {
      id: 15,
      title: "Soval Ref.A54",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img014.jpg'),
      category: "blusas",
    },
    {
      id: 16,
      title: "Soval Ref.A57",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img015.jpg'),
      category: "blusas",
    },
    {
      id: 17,
      title: "Soval Ref.137",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img016.jpg'),
      category: "blusas",
    },
    {
      id: 18,
      title: "Soval Ref.105",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img017.jpg'),
      category: "blusas",
    },
    {
      id: 19,
      title: "Soval Ref.109",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img018.jpg'),
      category: "blusas",
    },
    {
      id: 20,
      title: "Soval Ref.140",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img019.jpg'),
      category: "blusas",
    },
    {
      id: 21,
      title: "Soval Ref.151",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img025.jpg'),
      category: "blusas",
    },
    {
      id: 22,
      title: "Soval Ref.139",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img026.jpg'),
      category: "blusas",
    },
    {
      id: 23,
      title: "Soval Ref.150",
      priceUnit: 8000,
      priceWholesale: 5000,
      cantidad: 1,
      image: require('./images/img027.jpg'),
      category: "blusas",
    },
  ],
};

export default data;
