const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Soval Ref.A48",
      price: 401,
      image: require('./images/img01.jpg'),
      category: "blusas",
    },
    {
      id: 2,
      title: "Soval Ref.A25",
      price: 304,
      image: require('./images/img02.jpg'),
      category: "blusas",
    },
    {
      id: 3,
      title: "Soval Ref.095",
      price: 4700,
      image: require('./images/img03.jpg'),
      category: "blusas",
    },
    {
      id: 4,
      title: "Soval Ref.A66",
      price: 399,
      image: require('./images/img04.jpg'),
      category: "blusas",
    },
    {
      id: 5,
      title: "Soval Ref.108",
      price: 405,
      image: require('./images/img05.jpg'),
      category: "blusas",
    },
    {
      id: 6,
      title: "Soval Ref.A61",
      price: 285,
      image: require('./images/img06.jpg'),
      category: "blusas",
    },
    {
      id: 7,
      title: "Soval Ref.109",
      price: 360,
      image: require('./images/img07.jpg'),
      category: "blusas",
    },
    {
      id: 8,
      title: "Soval.Ref 113",
      price: 3355,
      image: require('./images/img020.jpg'),
      category: "blusas",
    },
    {
      id: 9,
      title: "Soval.Ref 136",
      price: 7999,
      image: require('./images/img021.jpg'),
      category: "blusas",
    },
    {
      id: 10,
      title: "Soval Ref.A56",
      price: 501,
      image: require('./images/img022.jpg'),
      category: "blusas",
    },
    {
      id: 11,
      title: "Soval Ref.115",
      price: 377,
      image: require('./images/img023.jpg'),
      category: "blusas",
    },
    {
      id: 12,
      title: "Soval Ref.093",
      price: 377,
      image: require('./images/img024.jpg'),
      category: "blusas",
    },
    {
      id: 13,
      title: "Soval Ref.095",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img012.jpg'),
      category: "blusas",
    },
    {
      id: 14,
      title: "Soval Ref.141",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img013.jpg'),
      category: "blusas",
    },
    {
      id: 15,
      title: "Soval Ref.A54",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img014.jpg'),
      category: "blusas",
    },
    {
      id: 16,
      title: "Soval Ref.A57",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img015.jpg'),
      category: "blusas",
    },
    {
      id: 17,
      title: "Soval Ref.137",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img016.jpg'),
      category: "blusas",
    },
    {
      id: 18,
      title: "Soval Ref.105",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img017.jpg'),
      category: "blusas",
    },
    {
      id: 19,
      title: "Soval Ref.109",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img018.jpg'),
      category: "blusas",
    },
    {
      id: 20,
      title: "Soval Ref.140",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img019.jpg'),
      category: "blusas",
    },
    {
      id: 21,
      title: "Soval Ref.151",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img025.jpg'),
      category: "blusas",
    },
    {
      id: 22,
      title: "Soval Ref.139",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img026.jpg'),
      category: "blusas",
    },
    {
      id: 23,
      title: "Soval Ref.150",
      price: "8000 unidad - 5000*Mayor",
      image: require('./images/img027.jpg'),
      category: "blusas",
    },
    
  ],
};

export default data;
